import React from 'react';
import { createStyles, Theme, makeStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import CssBaseline from '@material-ui/core/CssBaseline';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';
import Paper from '@material-ui/core/Paper';
import Fab from '@material-ui/core/Fab';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import ListItemText from '@material-ui/core/ListItemText';
import ListSubheader from '@material-ui/core/ListSubheader';
import Avatar from '@material-ui/core/Avatar';
import MenuIcon from '@material-ui/icons/Menu';
import AddIcon from '@material-ui/icons/Add';
import SearchIcon from '@material-ui/icons/Search';
import MoreIcon from '@material-ui/icons/MoreVert';
import InputLabel from '@material-ui/core/InputLabel';
import MenuItem from '@material-ui/core/MenuItem';
import FormHelperText from '@material-ui/core/FormHelperText';
import FormControl from '@material-ui/core/FormControl';
import Select from '@material-ui/core/Select';
import {Box, Grid, Slide, Slider} from "@material-ui/core";
const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];

const useStyles = makeStyles((theme: Theme) =>
    createStyles({
        text: {
            padding: theme.spacing(2, 2, 0),
        },
        paper: {
            paddingBottom: 50,
        },
        list: {
            marginBottom: theme.spacing(2),
        },
        subheader: {
            backgroundColor: theme.palette.background.paper,
        },
        formControl: {
            margin: theme.spacing(1),
            minWidth: 120,
        },
        selectEmpty: {
            marginTop: theme.spacing(2),
        },
        appBar: {
            top: 'auto',
            bottom: 0,
            zIndex: 1400,
        },
        appBarCenter: {
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto',
        },

        grow: {
            flexGrow: 1,
        },
        fabButton: {
            position: 'absolute',
            zIndex: 1,
            top: -30,
            left: 0,
            right: 0,
            margin: '0 auto',
        },
    }),
);

export default function BottomAppBar() {
    const classes = useStyles();
    const [value, setValue] = React.useState<number>(30);

    const handleChange = (event: any, newValue: number | number[]) => {
        setValue(newValue as number);
    };
    return (
        <React.Fragment>
            <CssBaseline />

            <AppBar position="fixed"  color="primary" className={classes.appBar}>

                <Toolbar>
                    <Grid container xs={12}  direction="row"
                          justify="space-between"
                          alignItems="center"

                    >

                        {/*
                        <Grid item xs={12} style={{marginLeft:"auto"}} display="flex"  className={classes.appBarCenter} flexGrow={1}>
                        */}
                            <Grid container item alignItems="center"
                                    xs={1} spacing={3} sm={3}>
                                <Grid item xs={2}>
                                    <Avatar variant="square">
                                        N
                                    </Avatar>
                                </Grid>

                                <Grid item xs={3}>
                                    <Typography noWrap>Song Title</Typography>
                                    <Typography noWrap>Artist Name</Typography>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton  color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton edge="end" color="inherit">
                                        <MenuIcon />
                                    </IconButton>
                                </Grid>
                            </Grid>
                            <Grid container item xs={4} spacing={1} sm={3} justify="space-evenly" >
                                <Grid item xs={1}>
                                    <IconButton edge="start" color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton  color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton  color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton  color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton edge="end" color="inherit">
                                        <MenuIcon />
                                    </IconButton>
                                </Grid>

                            </Grid>
                            <Grid container item xs={1} spacing={5} sm={3} justify="flex-end" alignItems="center">
                                <Grid item xs={1}>
                                    <IconButton edge="start" color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs={1}>
                                    <IconButton  color="inherit">
                                        <SearchIcon />
                                    </IconButton>
                                </Grid>

                                <Grid item xs={1}>
                                    <IconButton color="inherit">
                                        <MenuIcon />
                                    </IconButton>
                                </Grid>
                                <Grid item xs justify="center" >
                                    <Slider style={{color:"white"}} value={value} onChange={handleChange} aria-labelledby="continuous-slider" />
                                </Grid>

                        </Grid>

                        





                        {/*
                         <Box style={{marginLeft:"auto 0"}} display="flex" justifyContent="center">
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                        <IconButton edge="start" color="inherit" aria-label="open drawer">
                            <MenuIcon />
                        </IconButton>
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                        <IconButton edge="end" color="inherit" aria-label="open drawer">
                            <MenuIcon />
                        </IconButton>
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                    </Box>

                    <Box style={{marginLeft:"auto"}} display="flex" justifyContent="flex-end">
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                        <IconButton edge="start" color="inherit" aria-label="open drawer">
                            <MenuIcon />
                        </IconButton>
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                        <IconButton edge="end" color="inherit" aria-label="open drawer">
                            <MenuIcon />
                        </IconButton>
                        <IconButton  color="inherit">
                            <SearchIcon />
                        </IconButton>
                    </Box>

                        */}


                    </Grid>




                </Toolbar>
            </AppBar>
        </React.Fragment>
    );
}
